### ISSUE TITLE
Frequent errors about "Address in use"

### ISSUE THREAD

**Issue by lyricnz** [lyricnz/tplink_ess#21]
## Version of the custom_component
0.1.1

## Configuration
Three switches configured.  It's likely the issue is cause by concurrent queries, and listening to a single network port.

## Describe the bug
Errors in the HA logs

This error originated from a custom integration.

```text
Logger: tplink_ess_lib
Source: custom_components/tplink_ess/api.py:28
Integration: TPLink ESS (documentation, issues)
First occurred: 6 February 2023 at 13:40:36 (84 occurrences)
Last logged: 13:44:22

Problems with network interface: [Errno 98] Address in use
```

also (perhaps related)

```text
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/tplink_ess/binary_sensor.py:120
Integration: TPLink ESS (documentation, issues)
First occurred: 12:34:42 (1 occurrences)
Last logged: 12:34:42

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 182, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 330, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 135, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 390, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 566, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 606, in _async_write_ha_state
    available = self.available  # only call self.available once per update cycle
  File "/config/custom_components/tplink_ess/binary_sensor.py", line 120, in available
    or self._key in self.coordinator.data.get("hostname")
TypeError: argument of type 'NoneType' is not iterable
```

## Debug log

```text

Add your logs here.

```

**Comment by firstof9** [comment]
> Problems with network interface: [Errno 98] Address in use

This error is coming from the library.

Try changing the version of the library in your `manifest.json` to `0.4.4` from `0.4.3` and see if the issue persists.

**Comment by lyricnz** [comment]
Agree the the conflict is likely caused by concurrent use of the query (which requires binding to a static port) but (a) HA should synchronize/not do this concurrently, (b) should handle errors from library - if that's what's causing the second error.

Will bump the verison.

**Comment by lyricnz** [comment]
Still get error - see https://github.com/firstof9/tplink-ess-lib/pull/35#issuecomment-1421533687

**Comment by firstof9** [comment]
Just as an FYI, I was getting "address in use" messages on my single switch, this fix solved it for my specific use case.

**Comment by lyricnz** [comment]
Will make a PR to the underlying library to make a single UDP listener, then reuse it for all the queries.  This should make it fully asyncio and more parallelisable. And stop this error (which happens when multiple request-responses overlap)
